FROM docker.io/amazoncorretto:21 AS builder

WORKDIR /app

COPY . .
RUN ./gradlew clean bootJar --no-daemon

FROM docker.io/amazoncorretto:21

WORKDIR /app

COPY --from=builder /app/build/libs/*.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
