version: '3'

services:
  postgres:
    image: docker.io/postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    image: quay.io/keycloak/keycloak:26.2
    environment:
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password

      KC_HTTP_PORT: 9090
      KC_HEALTH_ENABLED: 'true'

      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command:
        - start-dev
        - --import-realm
    volumes:
        - ../src/main/resources/test-realm.json:/opt/keycloak/data/import/test-realm.json
    ports:
      - "9090:9090"
      - "9000:9000"
    depends_on:
      - postgres

  # Comment this service if you want to run the app locally without a containers
  keycloak-admin-api:
    build: ../.
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_URL: http://keycloak:9090
      KEYCLOAK_URL_MANAGEMENT: http://keycloak:9000
    depends_on:
      - keycloak

volumes:
  postgres_data:
